# Generated by Django 4.1.1 on 2022-09-09 04:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Company_Name', models.CharField(max_length=255)),
                ('Employment_type', models.CharField(choices=[('Full-time', 'Full-Time'), ('Contact', 'Contract'), ('Remote', 'Remote'), ('Part-time', 'Part-Time')], default='Remote', max_length=20)),
                ('Experience_level', models.CharField(blank=True, choices=[('ENTRY-LEVEL', 'Entry-Level'), ('MID-LEVEL', 'Mid-Level'), ('SENIOR', 'Senior')], max_length=20)),
                ('Desc', models.TextField()),
                ('job_desc', models.TextField()),
            ],
            options={
                'ordering': ('Company_Name',),
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('Last_name', models.CharField(max_length=40)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Linkedin_profile', models.CharField(max_length=100)),
                ('Github_profile', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Years_of_experience', models.CharField(blank=True, choices=[('0-1', '0-1'), ('1-2', '1-2'), ('3-4', '3-4'), ('5-6', '5-6'), ('7-Above', '7-Above')], max_length=100)),
                ('Cover_letter', models.TextField(blank=True, max_length=255, null=True)),
                ('Publish_status', models.CharField(blank=True, choices=[('unpublished', 'Unpublished'), ('published', 'Published')], max_length=20)),
                ('job_Advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='Api.jobadvert')),
            ],
        ),
    ]
