# Generated by Django 4.1.1 on 2022-09-09 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_jobadvert_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobadvert',
            options={'ordering': ('Publish_status',)},
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='Publish_status',
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='Publish_status',
            field=models.CharField(blank=True, choices=[('unpublished', 'Unpublished'), ('published', 'Published')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobadvert',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
