# Generated by Django 4.1.1 on 2022-09-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_jobadvert_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobadvert',
            options={'ordering': ('-Publish_status',)},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Github_profile',
            field=models.URLField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Linkedin_profile',
            field=models.URLField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Website',
            field=models.URLField(default='optional', max_length=100),
        ),
    ]
