# Generated by Django 4.1.1 on 2022-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_jobadvert_options_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobadvert',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
